pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    bat 'rmdir /s /q VisualTestingSeleniumWithCucumber'
					bat "git clone   https://github.com/KARIM-QA/VisualTestingSeleniumWithCucumber.git "
					
                }
            }
        }

        stage('Build') {
            steps {
                script {
                   bat """
				   cd VisualTestingSeleniumWithCucumber
				   mvn clean install
				   
				   """
                }
            }
        }

        stage('Publish & Deploy') {
            steps {
                script {
				
                    // Archive the results generated by the Robocorp task.
                    archiveArtifacts artifacts: 'VisualTestingSeleniumWithCucumber/output/*', allowEmptyArchive: true
                }
            }
        }
    }

    post {
        success {
            echo 'Test completed successfully !!!'
        }

        failure {
        echo 'Test Failed !!!'
        
         }
    }
}
