pipeline {
	agent any

	stages {
		stage('Clone Repository') {
			steps {
				script {
					bat 'rmdir /s /q VisualTestingSeleniumCucumberProject'
					bat "git clone   https://github.com/KARIM-QA/VisualTestingSeleniumCucumberProject.git "
				}
			}
		}

		stage('Build') {
			steps {
				script {
					bat """
				   cd VisualTestingSeleniumCucumberProject
				   mvn clean install
				   
				   """
				}
			}
		}

		stage('Publish & Deploy') {
			steps {
				script {
					// Archive the results generated by the task.
					archiveArtifacts artifacts: 'VisualTestingSeleniumCucumberProject/output/*', allowEmptyArchive: true, fingerprint: true, onlyIfSuccessful: true, excludes: 'VisualTestingSeleniumWithCucumber/output/screenshots/**', destination: 'C:/reports'
				}
			}
		}
	}

	post {
		success {
			echo 'Test completed successfully !!!'
		}

		failure {
			echo 'Test Failed !!!'
		}
	}
}
